version: "3.9"

services:
  nats:
    image: nats:2
    container_name: nats
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"  # monitoring

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    container_name: chat-web
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    ports:
      - "8000:8000"
    volumes:
      - chat_db:/app/chatroom.db
      - chat_history:/app/chatroom_prototype/message_history

  history:
    build:
      context: .
      dockerfile: docker/Dockerfile.history
    container_name: chat-history
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    volumes:
      - chat_history:/app/message_history

volumes:
  chat_db:
  chat_history:


