apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatroom-web
  template:
    metadata:
      labels:
        app: chatroom-web
    spec:
      containers:
        - name: chatroom-web
          image: luukmn/chatroom-web:latest
          ports:
            - containerPort: 8000
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
