name: Python CD

on:
  workflow_run:
    workflows: ["Python CI"]
    branches: [ cd ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
        repository: LuukMaessen-code/chatroom_prototype
        ref: cd
        path: chatroom_prototype

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Message History image
        uses: docker/build-push-action@v5
        with:
          context: ./chatroom_prototype
          file: ./docker/Dockerfile.history
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/message-history:cd-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/message-history:sha-${{ github.sha }}

      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: ./chatroom_prototype
          file: ./docker/Dockerfile.web
          push: true
          tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/message-web:cd-latest
          ${{ secrets.DOCKERHUB_USERNAME }}/message-web:sha-${{ github.sha }}

      # Verify images pushed
      - name: Verify images pushed
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/message-history:cd-latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/message-web:cd-latest
